In [14]:
import pandas as gyat
import hvplot.pandas

df = gyat.read_csv("covid.csv")

df[["Country/Region","Confirmed","Deaths", "Recovered"]]

         Country/Region  Confirmed  Deaths  Recovered
0           Afghanistan      36263    1269      25198
1               Albania       4880     144       2745
2               Algeria      27973    1163      18837
3               Andorra        907      52        803
4                Angola        950      41        242
..                  ...        ...     ...        ...
182  West Bank and Gaza      10621      78       3752
183      Western Sahara         10       1          8
184               Yemen       1691     483        833
185              Zambia       4552     140       2815
186            Zimbabwe       2704      36        542

[187 rows x 4 columns]

## Question 1

### Which country has the highest confirmed cases

In [15]:
df.sort_values(by = "Deaths", ascending = False)[["Country/Region", "Confirmed"]].head(1)

    Country/Region  Confirmed
173             US    4290259

## Question 2

### Which country has the highest deaths

In [16]:
df.sort_values(by = "Deaths", ascending = False)[["Country/Region", "Deaths"]].head(1)

    Country/Region  Deaths
173             US  148011

## Question 3

### Show Philippines Confirmed , Deaths , Recovered

In [17]:
df[df["Country/Region"] == "Philippines"][["Country/Region", "Confirmed", "Deaths", "Recovered"]]

    Country/Region  Confirmed  Deaths  Recovered
133    Philippines      82040    1945      26446

## Question 4

### Display Per WHO Region

In [18]:
df.groupby("WHO Region")[["Confirmed", "Deaths", "Recovered"]].sum()

                       Confirmed  Deaths  Recovered
WHO Region
Africa                    723207   12223     440645
Americas                 8839286  342732    4468616
Eastern Mediterranean    1490744   38339    1201400
Europe                   3299523  211144    1993723
South-East Asia          1835297   41349    1156933
Western Pacific           292428    8249     206770

## Question 5

### What is the average Deaths per WHO region

In [19]:
df.groupby("WHO Region")[["Deaths"]].mean().round(2)

                        Deaths
WHO Region
Africa                  254.65
Americas               9792.34
Eastern Mediterranean  1742.68
Europe                 3770.43
South-East Asia        4134.90
Western Pacific         515.56

## HVPLOT 1

### Total cases per WHO region

In [21]:
contint = df.groupby("WHO Region")[["Confirmed", "Deaths", "Recovered", "Active"]].sum()
contint["Confirmed"].hvplot.bar(title = "Total Confirmed Cases by WHO Region", ylabel = "Total Confirmed Cases", rot = 45)

:Bars   [WHO Region]   (Confirmed)

## HVPLOT 2

### confirmed and deaths

In [ ]:
contint[["Confirmed","Deaths"]].hvplot.line(title = "Confirmed Cases VS Deaths per WHO region",xlabel = "WHO region", ylabel = "Number of Cases")

:NdOverlay   [Variable]
   :Curve   [WHO Region]   (value)

## HVPLOT 3

### Total cases per WHO region

## HVPLOT 4

### Total cases per WHO region

## HVPLOT 5

### Total cases per WHO region